CREATE TABLE "public"."platform_task"
(
    "id"            BIGINT GENERATED BY DEFAULT AS IDENTITY primary key,
    "uid"           uuid                                        NOT NULL DEFAULT uuid_generate_v4(),
    "created_time"  timestamptz(6) NOT NULL,
    "created_by"    varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
    "updated_time"  timestamptz(6),
    "updated_by"    varchar(100) COLLATE "pg_catalog"."default",
    "deleted_time"  timestamptz(6),
    "deleted_by"    varchar(100) COLLATE "pg_catalog"."default",
    "task_name"     varchar(255),
    "expire_time"   timestamptz,
    "display_order" int4
);

CREATE TABLE "public"."member_task_recode"
(
    "id"            BIGINT GENERATED BY DEFAULT AS IDENTITY primary key,
    "uid"           uuid                                        NOT NULL DEFAULT uuid_generate_v4(),
    "created_time"  timestamptz(6) NOT NULL,
    "created_by"    varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
    "updated_time"  timestamptz(6),
    "updated_by"    varchar(100) COLLATE "pg_catalog"."default",
    "deleted_time"  timestamptz(6),
    "deleted_by"    varchar(100) COLLATE "pg_catalog"."default",
    "task_id"       int4,
    "complete_time" timestamptz,
    "member_id"     int4,
    CONSTRAINT "task_member" FOREIGN KEY ("member_id") REFERENCES "public"."member" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);