CREATE TABLE "public"."gpt_speech_text_recode"
(
    "id"           BIGINT GENERATED BY DEFAULT AS IDENTITY primary key,
    "uid"          uuid                                        NOT NULL DEFAULT uuid_generate_v4(),
    "created_time" timestamptz(6) NOT NULL,
    "created_by"   varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
    "updated_time" timestamptz(6),
    "updated_by"   varchar(100) COLLATE "pg_catalog"."default",
    "deleted_time" timestamptz(6),
    "deleted_by"   varchar(100) COLLATE "pg_catalog"."default",
    "key"          varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
    "content"      text,
    "member_id"    int4,
    "used"         bool                                                 default false,
    CONSTRAINT "gpt_speech_text_member" FOREIGN KEY ("member_id") REFERENCES "public"."member" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE
INDEX "unique_speech_text_key" ON "public"."gpt_speech_text_recode" USING btree (
  "key"
);
