-- user <-> role 中间表
CREATE TABLE "public"."sys_user_r_sys_role"
(
    "id"           BIGINT GENERATED BY DEFAULT AS IDENTITY primary key,
    "uid"          uuid                                        NOT NULL DEFAULT uuid_generate_v4(),
    "created_time" timestamptz(6) NOT NULL,
    "created_by"   varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
    "updated_time" timestamptz(6),
    "updated_by"   varchar(255) COLLATE "pg_catalog"."default",
    "deleted_time" timestamptz(6),
    "deleted_by"   varchar(255) COLLATE "pg_catalog"."default",
    "user_id"      int8                                        NOT NULL,
    "role_id"      int8                                        NOT NULL
);


insert into "public"."sys_role" ("code", "name", "description", "status", "created_time", "created_by")
values ('SYSADMIN', '超级管理员', '超级管理员', true, now(), 'ray');
insert into "public"."sys_role" ("code", "name", "description", "status", "created_time", "created_by")
values ('ADMIN', '管理员', '管理员', true, now(), 'ray');
insert into "public"."sys_role" ("code", "name", "description", "status", "created_time", "created_by")
values ('FINANCE', '财务', '财务', true, now(), 'ray');
insert into "public"."sys_role" ("code", "name", "description", "status", "created_time", "created_by")
values ('PROCURER', '采购', '采购', true, now(), 'ray');
insert into "public"."sys_role" ("code", "name", "description", "status", "created_time", "created_by")
values ('CUSTOMER', '客服', '客服', true, now(), 'ray');
