-- blog 表
CREATE TABLE "public"."blog"
(
    "id"                  BIGINT GENERATED BY DEFAULT AS IDENTITY primary key,
    "created_time"        timestamptz(6) NOT NULL,
    "created_by"          varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
    "updated_time"        timestamptz(6),
    "updated_by"          varchar(255) COLLATE "pg_catalog"."default",
    "deleted_time"        timestamptz(6),
    "deleted_by"          varchar(255) COLLATE "pg_catalog"."default",
    "uid"                 uuid                                        NOT NULL DEFAULT uuid_generate_v4(),
    "title"               varchar(255) COLLATE "pg_catalog"."default",
    "content"             text,
    "description"         varchar(255) COLLATE "pg_catalog"."default",
    "publish_time"        timestamptz(6),
    "active"              bool                                                 DEFAULT true,
    "allow_comment"       bool                                                 DEFAULT false,
    "comment_need_review" bool                                                 DEFAULT false,
    "banner_image"        varchar(255) COLLATE "pg_catalog"."default",
    "cover_image"         varchar(255) COLLATE "pg_catalog"."default",
    "is_hot"              bool                                                 DEFAULT false,
    "is_top"              bool                                                 DEFAULT false,
    "like_count"          int8                                                 DEFAULT 0,
    "unlike_count"        int8                                                 DEFAULT 0,
    "read_count"          int8                                                 DEFAULT 0,
    "comment_count"       int8                                                 DEFAULT 0,
    "author"              varchar(255) COLLATE "pg_catalog"."default",
    "type"                varchar(255) COLLATE "pg_catalog"."default",
    "ad_code"             varchar(255) COLLATE "pg_catalog"."default",
    longitude             DECIMAL(16, 4),
    latitude              DECIMAL(16, 4),
    "member_id"           int8
);

CREATE
INDEX "index_blog_id" ON "public"."blog" (
    "id",
    "uid",
    "title",
    "content",
    "ad_code",
    "author"
);

-- member collect blog 表
CREATE TABLE "public"."member_collect_blog"
(
    "id"           BIGINT GENERATED BY DEFAULT AS IDENTITY primary key,
    "created_time" timestamptz(6) NOT NULL,
    "created_by"   varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
    "updated_time" timestamptz(6),
    "updated_by"   varchar(255) COLLATE "pg_catalog"."default",
    "deleted_time" timestamptz(6),
    "deleted_by"   varchar(255) COLLATE "pg_catalog"."default",
    "uid"          uuid                                        NOT NULL DEFAULT uuid_generate_v4(),
    "member_id"    int8,
    "blog_id"      int8
);

CREATE
INDEX "index_member_collect_blog_id" ON "public"."member_collect_blog" (
  "id",
  "uid"
);

-- member like blog 表
CREATE TABLE "public"."member_like_blog"
(
    "id"           BIGINT GENERATED BY DEFAULT AS IDENTITY primary key,
    "created_time" timestamptz(6) NOT NULL,
    "created_by"   varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
    "updated_time" timestamptz(6),
    "updated_by"   varchar(255) COLLATE "pg_catalog"."default",
    "deleted_time" timestamptz(6),
    "deleted_by"   varchar(255) COLLATE "pg_catalog"."default",
    "uid"          uuid                                        NOT NULL DEFAULT uuid_generate_v4(),
    "member_id"    int8,
    "blog_id"      int8
);

CREATE
INDEX "index_member_like_blog_id" ON "public"."member_like_blog" (
  "id",
  "uid"
);

-- member like blog 表
CREATE TABLE "public"."member_read_history_blog"
(
    "id"           BIGINT GENERATED BY DEFAULT AS IDENTITY primary key,
    "created_time" timestamptz(6) NOT NULL,
    "created_by"   varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
    "updated_time" timestamptz(6),
    "updated_by"   varchar(255) COLLATE "pg_catalog"."default",
    "deleted_time" timestamptz(6),
    "deleted_by"   varchar(255) COLLATE "pg_catalog"."default",
    "uid"          uuid                                        NOT NULL DEFAULT uuid_generate_v4(),
    "member_id"    int8,
    "blog_id"      int8
);

CREATE
INDEX "index_member_read_history_blog_id" ON "public"."member_read_history_blog" (
  "id",
  "uid"
);



-- blog category 表
CREATE TABLE "public"."blog_category"
(
    "id"            BIGINT GENERATED BY DEFAULT AS IDENTITY primary key,
    "created_time"  timestamptz(6) NOT NULL,
    "created_by"    varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
    "updated_time"  timestamptz(6),
    "updated_by"    varchar(255) COLLATE "pg_catalog"."default",
    "deleted_time"  timestamptz(6),
    "deleted_by"    varchar(255) COLLATE "pg_catalog"."default",
    "uid"           uuid                                        NOT NULL DEFAULT uuid_generate_v4(),
    "category_key"  varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
    "name"          varchar(255) COLLATE "pg_catalog"."default",
    "description"   text,
    "active"        bool                                                 DEFAULT true,
    "parent_id"     int8,
    "display_order" int8,
    "is_hot"        bool                                                 DEFAULT false,
    "image"         varchar(255)
);

CREATE
INDEX "index_blog_category_id" ON "public"."blog_category" (
    "id",
    "uid",
    "name"
);



-- blog <-> blog category 中间表
CREATE TABLE "public"."blog_r_blog_category"
(
    "id"           BIGINT GENERATED BY DEFAULT AS IDENTITY primary key,
    "uid"          uuid                                        NOT NULL DEFAULT uuid_generate_v4(),
    "created_time" timestamptz(6) NOT NULL,
    "created_by"   varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
    "updated_time" timestamptz(6),
    "updated_by"   varchar(255) COLLATE "pg_catalog"."default",
    "deleted_time" timestamptz(6),
    "deleted_by"   varchar(255) COLLATE "pg_catalog"."default",
    "blog_id"      int8                                        NOT NULL,
    "category_id"  int8                                        NOT NULL
);


-- blog comment 表
CREATE TABLE "public"."blog_comment"
(
    "id"           BIGINT GENERATED BY DEFAULT AS IDENTITY primary key,
    "created_time" timestamptz(6) NOT NULL,
    "created_by"   varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
    "updated_time" timestamptz(6),
    "updated_by"   varchar(255) COLLATE "pg_catalog"."default",
    "deleted_time" timestamptz(6),
    "deleted_by"   varchar(255) COLLATE "pg_catalog"."default",
    "uid"          uuid                                        NOT NULL DEFAULT uuid_generate_v4(),
    "blog_id"      int8                                        NOT NULL,
    "parent_id"    int8,
    "level"        int8,
    "active"       bool                                                 DEFAULT true,
    "image"        varchar(255) COLLATE "pg_catalog"."default",
    "content"      text,
    "is_hot"       bool                                                 DEFAULT false,
    "is_top"       bool                                                 DEFAULT false,
    "like_count"   int8                                                 DEFAULT 0,
    "unlike_count" int8                                                 DEFAULT 0,
    "reply_count"  int8                                                 DEFAULT 0,
    "member_id"    int8                                        NOT NULL,
    "member_name"  varchar(255) COLLATE "pg_catalog"."default"
);

CREATE
INDEX "index_blog_comment_id_code" ON "public"."blog_comment" USING btree (
  "id",
  "uid"
);