CREATE TABLE "public"."portal_menu"
(
    "id"           BIGINT GENERATED BY DEFAULT AS IDENTITY primary key,
    "uid"          uuid                                        NOT NULL DEFAULT uuid_generate_v4(),
    "created_time" timestamptz(6) NOT NULL,
    "created_by"   varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
    "updated_time" timestamptz(6),
    "updated_by"   varchar(100) COLLATE "pg_catalog"."default",
    "deleted_time" timestamptz(6),
    "deleted_by"   varchar(100) COLLATE "pg_catalog"."default",
    "name"         varchar(255)                                NOT NULL,
    "description"  varchar(255),
    "icon"         varchar(255),
    "enable"       bool                                                 DEFAULT true
);

CREATE
INDEX "index_portal_menu" ON "public"."portal_menu" USING btree (
  "id",
  "uid",
  "name"
);
